/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpiritsRouteImport } from './routes/spirits'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpiritsIndexRouteImport } from './routes/spirits.index'
import { Route as SpiritsSlugRouteImport } from './routes/spirits.$slug'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AdminOpeningsRouteImport } from './routes/_admin/openings'
import { Route as SpiritsSlugAspectRouteImport } from './routes/spirits.$slug.$aspect'
import { Route as AdminOpeningsNewRouteImport } from './routes/_admin/openings/new'
import { Route as AdminOpeningsIdEditRouteImport } from './routes/_admin/openings/$id.edit'

const SpiritsRoute = SpiritsRouteImport.update({
  id: '/spirits',
  path: '/spirits',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiritsIndexRoute = SpiritsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpiritsRoute,
} as any)
const SpiritsSlugRoute = SpiritsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpiritsRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminOpeningsRoute = AdminOpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => AdminRoute,
} as any)
const SpiritsSlugAspectRoute = SpiritsSlugAspectRouteImport.update({
  id: '/$aspect',
  path: '/$aspect',
  getParentRoute: () => SpiritsSlugRoute,
} as any)
const AdminOpeningsNewRoute = AdminOpeningsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminOpeningsRoute,
} as any)
const AdminOpeningsIdEditRoute = AdminOpeningsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminOpeningsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/spirits': typeof SpiritsRouteWithChildren
  '/openings': typeof AdminOpeningsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/spirits/$slug': typeof SpiritsSlugRouteWithChildren
  '/spirits/': typeof SpiritsIndexRoute
  '/openings/new': typeof AdminOpeningsNewRoute
  '/spirits/$slug/$aspect': typeof SpiritsSlugAspectRoute
  '/openings/$id/edit': typeof AdminOpeningsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/openings': typeof AdminOpeningsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/spirits/$slug': typeof SpiritsSlugRouteWithChildren
  '/spirits': typeof SpiritsIndexRoute
  '/openings/new': typeof AdminOpeningsNewRoute
  '/spirits/$slug/$aspect': typeof SpiritsSlugAspectRoute
  '/openings/$id/edit': typeof AdminOpeningsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/credits': typeof CreditsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/spirits': typeof SpiritsRouteWithChildren
  '/_admin/openings': typeof AdminOpeningsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/spirits/$slug': typeof SpiritsSlugRouteWithChildren
  '/spirits/': typeof SpiritsIndexRoute
  '/_admin/openings/new': typeof AdminOpeningsNewRoute
  '/spirits/$slug/$aspect': typeof SpiritsSlugAspectRoute
  '/_admin/openings/$id/edit': typeof AdminOpeningsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credits'
    | '/search'
    | '/settings'
    | '/spirits'
    | '/openings'
    | '/profile'
    | '/sign-in/$'
    | '/spirits/$slug'
    | '/spirits/'
    | '/openings/new'
    | '/spirits/$slug/$aspect'
    | '/openings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credits'
    | '/search'
    | '/settings'
    | '/openings'
    | '/profile'
    | '/sign-in/$'
    | '/spirits/$slug'
    | '/spirits'
    | '/openings/new'
    | '/spirits/$slug/$aspect'
    | '/openings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/credits'
    | '/search'
    | '/settings'
    | '/spirits'
    | '/_admin/openings'
    | '/_authenticated/profile'
    | '/sign-in/$'
    | '/spirits/$slug'
    | '/spirits/'
    | '/_admin/openings/new'
    | '/spirits/$slug/$aspect'
    | '/_admin/openings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CreditsRoute: typeof CreditsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SpiritsRoute: typeof SpiritsRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spirits': {
      id: '/spirits'
      path: '/spirits'
      fullPath: '/spirits'
      preLoaderRoute: typeof SpiritsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spirits/': {
      id: '/spirits/'
      path: '/'
      fullPath: '/spirits/'
      preLoaderRoute: typeof SpiritsIndexRouteImport
      parentRoute: typeof SpiritsRoute
    }
    '/spirits/$slug': {
      id: '/spirits/$slug'
      path: '/$slug'
      fullPath: '/spirits/$slug'
      preLoaderRoute: typeof SpiritsSlugRouteImport
      parentRoute: typeof SpiritsRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/openings': {
      id: '/_admin/openings'
      path: '/openings'
      fullPath: '/openings'
      preLoaderRoute: typeof AdminOpeningsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/spirits/$slug/$aspect': {
      id: '/spirits/$slug/$aspect'
      path: '/$aspect'
      fullPath: '/spirits/$slug/$aspect'
      preLoaderRoute: typeof SpiritsSlugAspectRouteImport
      parentRoute: typeof SpiritsSlugRoute
    }
    '/_admin/openings/new': {
      id: '/_admin/openings/new'
      path: '/new'
      fullPath: '/openings/new'
      preLoaderRoute: typeof AdminOpeningsNewRouteImport
      parentRoute: typeof AdminOpeningsRoute
    }
    '/_admin/openings/$id/edit': {
      id: '/_admin/openings/$id/edit'
      path: '/$id/edit'
      fullPath: '/openings/$id/edit'
      preLoaderRoute: typeof AdminOpeningsIdEditRouteImport
      parentRoute: typeof AdminOpeningsRoute
    }
  }
}

interface AdminOpeningsRouteChildren {
  AdminOpeningsNewRoute: typeof AdminOpeningsNewRoute
  AdminOpeningsIdEditRoute: typeof AdminOpeningsIdEditRoute
}

const AdminOpeningsRouteChildren: AdminOpeningsRouteChildren = {
  AdminOpeningsNewRoute: AdminOpeningsNewRoute,
  AdminOpeningsIdEditRoute: AdminOpeningsIdEditRoute,
}

const AdminOpeningsRouteWithChildren = AdminOpeningsRoute._addFileChildren(
  AdminOpeningsRouteChildren,
)

interface AdminRouteChildren {
  AdminOpeningsRoute: typeof AdminOpeningsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOpeningsRoute: AdminOpeningsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SpiritsSlugRouteChildren {
  SpiritsSlugAspectRoute: typeof SpiritsSlugAspectRoute
}

const SpiritsSlugRouteChildren: SpiritsSlugRouteChildren = {
  SpiritsSlugAspectRoute: SpiritsSlugAspectRoute,
}

const SpiritsSlugRouteWithChildren = SpiritsSlugRoute._addFileChildren(
  SpiritsSlugRouteChildren,
)

interface SpiritsRouteChildren {
  SpiritsSlugRoute: typeof SpiritsSlugRouteWithChildren
  SpiritsIndexRoute: typeof SpiritsIndexRoute
}

const SpiritsRouteChildren: SpiritsRouteChildren = {
  SpiritsSlugRoute: SpiritsSlugRouteWithChildren,
  SpiritsIndexRoute: SpiritsIndexRoute,
}

const SpiritsRouteWithChildren =
  SpiritsRoute._addFileChildren(SpiritsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CreditsRoute: CreditsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SpiritsRoute: SpiritsRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
