/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpiritsRouteImport } from './routes/spirits'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpiritsIndexRouteImport } from './routes/spirits.index'
import { Route as SpiritsSlugRouteImport } from './routes/spirits.$slug'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as SpiritsSlugAspectRouteImport } from './routes/spirits.$slug.$aspect'

const SpiritsRoute = SpiritsRouteImport.update({
  id: '/spirits',
  path: '/spirits',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiritsIndexRoute = SpiritsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpiritsRoute,
} as any)
const SpiritsSlugRoute = SpiritsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpiritsRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SpiritsSlugAspectRoute = SpiritsSlugAspectRouteImport.update({
  id: '/$aspect',
  path: '/$aspect',
  getParentRoute: () => SpiritsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/settings': typeof SettingsRoute
  '/spirits': typeof SpiritsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/spirits/$slug': typeof SpiritsSlugRouteWithChildren
  '/spirits/': typeof SpiritsIndexRoute
  '/spirits/$slug/$aspect': typeof SpiritsSlugAspectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/settings': typeof SettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/spirits/$slug': typeof SpiritsSlugRouteWithChildren
  '/spirits': typeof SpiritsIndexRoute
  '/spirits/$slug/$aspect': typeof SpiritsSlugAspectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/credits': typeof CreditsRoute
  '/settings': typeof SettingsRoute
  '/spirits': typeof SpiritsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/spirits/$slug': typeof SpiritsSlugRouteWithChildren
  '/spirits/': typeof SpiritsIndexRoute
  '/spirits/$slug/$aspect': typeof SpiritsSlugAspectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credits'
    | '/settings'
    | '/spirits'
    | '/profile'
    | '/sign-in/$'
    | '/spirits/$slug'
    | '/spirits/'
    | '/spirits/$slug/$aspect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credits'
    | '/settings'
    | '/profile'
    | '/sign-in/$'
    | '/spirits/$slug'
    | '/spirits'
    | '/spirits/$slug/$aspect'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/credits'
    | '/settings'
    | '/spirits'
    | '/_authenticated/profile'
    | '/sign-in/$'
    | '/spirits/$slug'
    | '/spirits/'
    | '/spirits/$slug/$aspect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CreditsRoute: typeof CreditsRoute
  SettingsRoute: typeof SettingsRoute
  SpiritsRoute: typeof SpiritsRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spirits': {
      id: '/spirits'
      path: '/spirits'
      fullPath: '/spirits'
      preLoaderRoute: typeof SpiritsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spirits/': {
      id: '/spirits/'
      path: '/'
      fullPath: '/spirits/'
      preLoaderRoute: typeof SpiritsIndexRouteImport
      parentRoute: typeof SpiritsRoute
    }
    '/spirits/$slug': {
      id: '/spirits/$slug'
      path: '/$slug'
      fullPath: '/spirits/$slug'
      preLoaderRoute: typeof SpiritsSlugRouteImport
      parentRoute: typeof SpiritsRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/spirits/$slug/$aspect': {
      id: '/spirits/$slug/$aspect'
      path: '/$aspect'
      fullPath: '/spirits/$slug/$aspect'
      preLoaderRoute: typeof SpiritsSlugAspectRouteImport
      parentRoute: typeof SpiritsSlugRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SpiritsSlugRouteChildren {
  SpiritsSlugAspectRoute: typeof SpiritsSlugAspectRoute
}

const SpiritsSlugRouteChildren: SpiritsSlugRouteChildren = {
  SpiritsSlugAspectRoute: SpiritsSlugAspectRoute,
}

const SpiritsSlugRouteWithChildren = SpiritsSlugRoute._addFileChildren(
  SpiritsSlugRouteChildren,
)

interface SpiritsRouteChildren {
  SpiritsSlugRoute: typeof SpiritsSlugRouteWithChildren
  SpiritsIndexRoute: typeof SpiritsIndexRoute
}

const SpiritsRouteChildren: SpiritsRouteChildren = {
  SpiritsSlugRoute: SpiritsSlugRouteWithChildren,
  SpiritsIndexRoute: SpiritsIndexRoute,
}

const SpiritsRouteWithChildren =
  SpiritsRoute._addFileChildren(SpiritsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CreditsRoute: CreditsRoute,
  SettingsRoute: SettingsRoute,
  SpiritsRoute: SpiritsRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
