/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpiritsRouteImport } from './routes/spirits'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as AdversariesRouteImport } from './routes/adversaries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpiritsIndexRouteImport } from './routes/spirits.index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as AdversariesIndexRouteImport } from './routes/adversaries.index'
import { Route as SpiritsSlugRouteImport } from './routes/spirits.$slug'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as GamesNewRouteImport } from './routes/games/new'
import { Route as GamesImportRouteImport } from './routes/games/import'
import { Route as GamesIdRouteImport } from './routes/games/$id'
import { Route as AdversariesSlugRouteImport } from './routes/adversaries.$slug'
import { Route as SpiritsSlugAspectRouteImport } from './routes/spirits.$slug.$aspect'

const SpiritsRoute = SpiritsRouteImport.update({
  id: '/spirits',
  path: '/spirits',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdversariesRoute = AdversariesRouteImport.update({
  id: '/adversaries',
  path: '/adversaries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiritsIndexRoute = SpiritsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpiritsRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const AdversariesIndexRoute = AdversariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdversariesRoute,
} as any)
const SpiritsSlugRoute = SpiritsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpiritsRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GamesRoute,
} as any)
const GamesImportRoute = GamesImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => GamesRoute,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GamesRoute,
} as any)
const AdversariesSlugRoute = AdversariesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdversariesRoute,
} as any)
const SpiritsSlugAspectRoute = SpiritsSlugAspectRouteImport.update({
  id: '/$aspect',
  path: '/$aspect',
  getParentRoute: () => SpiritsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adversaries': typeof AdversariesRouteWithChildren
  '/credits': typeof CreditsRoute
  '/games': typeof GamesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spirits': typeof SpiritsRouteWithChildren
  '/adversaries/$slug': typeof AdversariesSlugRoute
  '/games/$id': typeof GamesIdRoute
  '/games/import': typeof GamesImportRoute
  '/games/new': typeof GamesNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/spirits/$slug': typeof SpiritsSlugRouteWithChildren
  '/adversaries/': typeof AdversariesIndexRoute
  '/games/': typeof GamesIndexRoute
  '/spirits/': typeof SpiritsIndexRoute
  '/spirits/$slug/$aspect': typeof SpiritsSlugAspectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/settings': typeof SettingsRoute
  '/adversaries/$slug': typeof AdversariesSlugRoute
  '/games/$id': typeof GamesIdRoute
  '/games/import': typeof GamesImportRoute
  '/games/new': typeof GamesNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/spirits/$slug': typeof SpiritsSlugRouteWithChildren
  '/adversaries': typeof AdversariesIndexRoute
  '/games': typeof GamesIndexRoute
  '/spirits': typeof SpiritsIndexRoute
  '/spirits/$slug/$aspect': typeof SpiritsSlugAspectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adversaries': typeof AdversariesRouteWithChildren
  '/credits': typeof CreditsRoute
  '/games': typeof GamesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spirits': typeof SpiritsRouteWithChildren
  '/adversaries/$slug': typeof AdversariesSlugRoute
  '/games/$id': typeof GamesIdRoute
  '/games/import': typeof GamesImportRoute
  '/games/new': typeof GamesNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/spirits/$slug': typeof SpiritsSlugRouteWithChildren
  '/adversaries/': typeof AdversariesIndexRoute
  '/games/': typeof GamesIndexRoute
  '/spirits/': typeof SpiritsIndexRoute
  '/spirits/$slug/$aspect': typeof SpiritsSlugAspectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adversaries'
    | '/credits'
    | '/games'
    | '/settings'
    | '/spirits'
    | '/adversaries/$slug'
    | '/games/$id'
    | '/games/import'
    | '/games/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/spirits/$slug'
    | '/adversaries/'
    | '/games/'
    | '/spirits/'
    | '/spirits/$slug/$aspect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credits'
    | '/settings'
    | '/adversaries/$slug'
    | '/games/$id'
    | '/games/import'
    | '/games/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/spirits/$slug'
    | '/adversaries'
    | '/games'
    | '/spirits'
    | '/spirits/$slug/$aspect'
  id:
    | '__root__'
    | '/'
    | '/adversaries'
    | '/credits'
    | '/games'
    | '/settings'
    | '/spirits'
    | '/adversaries/$slug'
    | '/games/$id'
    | '/games/import'
    | '/games/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/spirits/$slug'
    | '/adversaries/'
    | '/games/'
    | '/spirits/'
    | '/spirits/$slug/$aspect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdversariesRoute: typeof AdversariesRouteWithChildren
  CreditsRoute: typeof CreditsRoute
  GamesRoute: typeof GamesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SpiritsRoute: typeof SpiritsRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spirits': {
      id: '/spirits'
      path: '/spirits'
      fullPath: '/spirits'
      preLoaderRoute: typeof SpiritsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adversaries': {
      id: '/adversaries'
      path: '/adversaries'
      fullPath: '/adversaries'
      preLoaderRoute: typeof AdversariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spirits/': {
      id: '/spirits/'
      path: '/'
      fullPath: '/spirits/'
      preLoaderRoute: typeof SpiritsIndexRouteImport
      parentRoute: typeof SpiritsRoute
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/adversaries/': {
      id: '/adversaries/'
      path: '/'
      fullPath: '/adversaries/'
      preLoaderRoute: typeof AdversariesIndexRouteImport
      parentRoute: typeof AdversariesRoute
    }
    '/spirits/$slug': {
      id: '/spirits/$slug'
      path: '/$slug'
      fullPath: '/spirits/$slug'
      preLoaderRoute: typeof SpiritsSlugRouteImport
      parentRoute: typeof SpiritsRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/new': {
      id: '/games/new'
      path: '/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/import': {
      id: '/games/import'
      path: '/import'
      fullPath: '/games/import'
      preLoaderRoute: typeof GamesImportRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/adversaries/$slug': {
      id: '/adversaries/$slug'
      path: '/$slug'
      fullPath: '/adversaries/$slug'
      preLoaderRoute: typeof AdversariesSlugRouteImport
      parentRoute: typeof AdversariesRoute
    }
    '/spirits/$slug/$aspect': {
      id: '/spirits/$slug/$aspect'
      path: '/$aspect'
      fullPath: '/spirits/$slug/$aspect'
      preLoaderRoute: typeof SpiritsSlugAspectRouteImport
      parentRoute: typeof SpiritsSlugRoute
    }
  }
}

interface AdversariesRouteChildren {
  AdversariesSlugRoute: typeof AdversariesSlugRoute
  AdversariesIndexRoute: typeof AdversariesIndexRoute
}

const AdversariesRouteChildren: AdversariesRouteChildren = {
  AdversariesSlugRoute: AdversariesSlugRoute,
  AdversariesIndexRoute: AdversariesIndexRoute,
}

const AdversariesRouteWithChildren = AdversariesRoute._addFileChildren(
  AdversariesRouteChildren,
)

interface GamesRouteChildren {
  GamesIdRoute: typeof GamesIdRoute
  GamesImportRoute: typeof GamesImportRoute
  GamesNewRoute: typeof GamesNewRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesIdRoute: GamesIdRoute,
  GamesImportRoute: GamesImportRoute,
  GamesNewRoute: GamesNewRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface SpiritsSlugRouteChildren {
  SpiritsSlugAspectRoute: typeof SpiritsSlugAspectRoute
}

const SpiritsSlugRouteChildren: SpiritsSlugRouteChildren = {
  SpiritsSlugAspectRoute: SpiritsSlugAspectRoute,
}

const SpiritsSlugRouteWithChildren = SpiritsSlugRoute._addFileChildren(
  SpiritsSlugRouteChildren,
)

interface SpiritsRouteChildren {
  SpiritsSlugRoute: typeof SpiritsSlugRouteWithChildren
  SpiritsIndexRoute: typeof SpiritsIndexRoute
}

const SpiritsRouteChildren: SpiritsRouteChildren = {
  SpiritsSlugRoute: SpiritsSlugRouteWithChildren,
  SpiritsIndexRoute: SpiritsIndexRoute,
}

const SpiritsRouteWithChildren =
  SpiritsRoute._addFileChildren(SpiritsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdversariesRoute: AdversariesRouteWithChildren,
  CreditsRoute: CreditsRoute,
  GamesRoute: GamesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SpiritsRoute: SpiritsRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
